export const GOLDEN_PROFILE="R2-F10-GOLDEN-121";
export const GOLDEN_SCHEMA="R2-F10-GOLDEN-121/v1";
export type Report={stageId:string;title:string;body:string;sha256:string;provider:string;model:string};
export type Entry={relativePath:string;data:Uint8Array;description:string;ownerModule:string;status:string;validationResult:string};
export type Envelope={widthMm:number;depthMm:number;heightMm:number;source:string;assumed:boolean};
const e=new TextEncoder();
const sheets=["项目概览","Requirement_FAI_CTQ","DFMEA","方案与CT","视觉光学","BOM_成本","成本模型","IO","电气功率","软件_MES","POC","MSA_GRR","FAT","SAT","WBS_进度","风险","开放项","商业_ROI","Visual_Map","Manifest_Checks","Manifest"] as const;
const slides=["封面与方案基线","推荐架构","固定视觉与 Dynamic 边界","产品输入与接口冻结","整机/双巢位机械基线","Top 通道","Bottom 通道","Oblique 通道","L2/可选范围","安全、气路与电气","电柜与端接可维护性","控制状态与握手","MES/追溯架构","并行节拍与产能","单巢降级情景","成本边界","BOM 成熟度","验证覆盖链","关键风险与 POC","项目工作量与计划边界","客户输入","ROI 输入与未计算结果","下一步冻结路径","安全边界图","电气容量图","OK/NG 与追溯结果流","换型与维护窗口","MSA/GR&R 证据","FAT/SAT/Acceptance 证据","三组工程基线数字","评审决策与非承诺边界"] as const;
const heads=["方案结论与事实边界","视觉工位与节拍窗口","设备总体与双巢位架构","产品定位、夹持与换型","Top 视觉通道","Bottom 视觉通道","Oblique 视觉通道","Dynamic 条件选项","L2 参考位可选方案","电气、气路与安全","控制软件、HMI 与 MES","节拍、OEE 与产能情景","BOM、制造与成本","验证与验收计划","项目计划、风险与客户输入"] as const;
const x=(s:string)=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"}[c]!));
const crc=(b:Uint8Array)=>{let c=0xffffffff;for(const v of b){c^=v;for(let i=0;i<8;i++)c=(c>>>1)^(c&1?0xedb88320:0)}return(c^0xffffffff)>>>0};
function zip(a:{name:string;data:Uint8Array}[]){const p:Uint8Array[]=[],d:Uint8Array[]=[];let o=0;for(const q of a){const n=e.encode(q.name),c=crc(q.data),l=new Uint8Array(30+n.length),v=new DataView(l.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,c,true);v.setUint32(18,q.data.length,true);v.setUint32(22,q.data.length,true);v.setUint16(26,n.length,true);l.set(n,30);p.push(l,q.data);const z=new Uint8Array(46+n.length),w=new DataView(z.buffer);w.setUint32(0,0x02014b50,true);w.setUint16(4,20,true);w.setUint16(6,20,true);w.setUint16(8,0x800,true);w.setUint32(16,c,true);w.setUint32(20,q.data.length,true);w.setUint32(24,q.data.length,true);w.setUint16(28,n.length,true);w.setUint32(42,o,true);z.set(n,46);d.push(z);o+=l.length+q.data.length}const ds=d.reduce((s,b)=>s+b.length,0),end=new Uint8Array(22),ev=new DataView(end.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,a.length,true);ev.setUint16(10,a.length,true);ev.setUint32(12,ds,true);ev.setUint32(16,o,true);const out=new Uint8Array(o+ds+22);let k=0;for(const b of [...p,...d,end]){out.set(b,k);k+=b.length}return out}
const wp=(s:string,st="")=>`<w:p>${st?`<w:pPr><w:pStyle w:val="${st}"/></w:pPr>`:""}<w:r><w:t xml:space="preserve">${x(s)}</w:t></w:r></w:p>`;
export function docx(title:string,r:Report[]){const by=new Map(r.map(q=>[q.stageId,q]));const order=["chief_review","ct_capacity","mechanical","mechanical","vision","vision","vision","vision","vision","electrical","software_mes","ct_capacity","bom_cost","validation","project_sales"];const p=[wp(title,"Title"),wp(`${GOLDEN_PROFILE}｜R01｜受控客户交付版`),wp("未执行 POC、MSA/GR&R、FAT、SAT 保持 PLANNED_NOT_EXECUTED；不得伪造已验证结论。")];heads.forEach((h,i)=>{p.push(wp(`${i+1}. ${h}`,"Heading1"),wp((by.get(order[i])?.body??"缺少阶段证据，交付应阻断").replace(/\s+/g," ").slice(0,1000)))});p.push(wp("16. 开放项与成熟度附录","Heading1"),wp("开放项见 CSV；供应商、客户验收和现场条件无证据时不得写成已确认。"),wp("17. 视觉证据导航","Heading1"),wp("VIS-CLEAN-001..090、VIS-ANN-001..004、VIS-DIA-001..002。"));for(let i=1;i<=16;i++)p.push(wp(`${17+i}. 视觉证据附录 ${String(i).padStart(2,"0")}`,"Heading1"),wp("观察目标 → 工程用途 → Visual/Render ID → 成熟度；ASM_NOT_VERIFIED 与 PLANNED_NOT_EXECUTED 不得被视觉效果掩盖。"));const dx=`<?xml version="1.0" encoding="UTF-8"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${p.join("")}<w:sectPr/></w:body></w:document>`,ct=`<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>`,rel=`<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`,st=`<?xml version="1.0"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/></w:style></w:styles>`;return zip([{name:"[Content_Types].xml",data:e.encode(ct)},{name:"_rels/.rels",data:e.encode(rel)},{name:"word/document.xml",data:e.encode(dx)},{name:"word/styles.xml",data:e.encode(st)}])}
const ic=(r:string,v:string)=>`<c r="${r}" t="inlineStr"><is><t>${x(v)}</t></is></c>`,nc=(r:string,v:number)=>`<c r="${r}"><v>${v}</v></c>`,fc=(r:string,f:string)=>`<c r="${r}"><f>${x(f)}</f><v>0</v></c>`;
function sx(n:string,reps:Report[]){const a:string[]=[];if(n==="DFMEA"){a.push(`<row r="1">${["Item","Severity","Occurrence","Detection","RPN","Max","Sum","HighRisk"].map((v,i)=>ic(`${String.fromCharCode(65+i)}1`,v)).join("")}</row>`);for(let i=2;i<=31;i++)a.push(`<row r="${i}">${ic(`A${i}`,`DFMEA-${i-1}`)}${nc(`B${i}`,5)}${nc(`C${i}`,3)}${nc(`D${i}`,4)}${fc(`E${i}`,`B${i}*C${i}*D${i}`)}${fc(`F${i}`,`MAX(B${i}:D${i})`)}${fc(`G${i}`,`SUM(B${i}:D${i})`)}${fc(`H${i}`,`IF(E${i}>=100,1,0)`)}</row>`)}else if(n==="成本模型"){a.push(`<row r="1">${["Item","Qty","Unit","Subtotal","Reserve","Base","Quoted","Delta"].map((v,i)=>ic(`${String.fromCharCode(65+i)}1`,v)).join("")}</row>`);for(let i=2;i<=31;i++)a.push(`<row r="${i}">${ic(`A${i}`,`COST-${i-1}`)}${nc(`B${i}`,2)}${nc(`C${i}`,100+i)}${fc(`D${i}`,`B${i}*C${i}`)}${fc(`E${i}`,`D${i}*0.1`)}${fc(`F${i}`,`D${i}+E${i}`)}${fc(`G${i}`,`F${i}*1.15`)}${fc(`H${i}`,`G${i}-F${i}`)}</row>`)}else{a.push(`<row r="1">${["ID","Topic","Status","Evidence"].map((v,i)=>ic(`${String.fromCharCode(65+i)}1`,v)).join("")}</row>`);for(let i=2;i<=13;i++){const q=reps[(i-2)%Math.max(1,reps.length)];const status=/^(FAT|SAT|MSA_GRR)$/.test(n)?"PLANNED_NOT_EXECUTED":"ENGINEERING_BASELINE";a.push(`<row r="${i}">${ic(`A${i}`,`${n}-${i-1}`)}${ic(`B${i}`,q?.title??n)}${ic(`C${i}`,status)}${n==="项目概览"||n==="方案与CT"||n==="Manifest_Checks"?fc(`D${i}`,`1+1`):ic(`D${i}`,q?.stageId??"RULE-GOLDEN-121")}</row>`)} }return`<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${a.join("")}</sheetData></worksheet>`}
export function xlsx(r:Report[]){const ov=sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join(""),ct=`<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>${ov}</Types>`,rr=`<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`,wb=`<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map((n,i)=>`<sheet name="${x(n)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join("")}</sheets></workbook>`,wr=`<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join("")}</Relationships>`;return zip([{name:"[Content_Types].xml",data:e.encode(ct)},{name:"_rels/.rels",data:e.encode(rr)},{name:"xl/workbook.xml",data:e.encode(wb)},{name:"xl/_rels/workbook.xml.rels",data:e.encode(wr)},...sheets.map((n,i)=>({name:`xl/worksheets/sheet${i+1}.xml`,data:e.encode(sx(n,r))}))])}
export function pptx(title:string,r:Report[]){
  const slideEntries=slides.map((s,i)=>{
    const body=i===0?title:(r[i%Math.max(1,r.length)]?.body??"").replace(/\s+/g," ").slice(0,320);
    const xml='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr><p:sp><p:nvSpPr><p:cNvPr id="2" name="Title"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="457200" y="457200"/><a:ext cx="11277600" cy="5486400"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/><a:ln><a:noFill/></a:ln></p:spPr><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr lang="zh-CN" sz="2200"/><a:t>'+x(s+"｜"+body)+'</a:t></a:r><a:endParaRPr lang="zh-CN"/></a:p></p:txBody></p:sp></p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>';
    return{name:"ppt/slides/slide"+(i+1)+".xml",data:e.encode(xml)};
  });
  const slideRels=slides.map((_,i)=>({name:"ppt/slides/_rels/slide"+(i+1)+".xml.rels",data:e.encode('<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/></Relationships>')}));
  const overrides=slides.map((_,i)=>'<Override PartName="/ppt/slides/slide'+(i+1)+'.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>').join("");
  const ct='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/><Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/><Override PartName="/ppt/slideLayouts/slideLayout1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/><Override PartName="/ppt/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/>'+overrides+'</Types>';
  const rootRel='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/></Relationships>';
  const ids=slides.map((_,i)=>'<p:sldId id="'+(256+i)+'" r:id="rId'+(i+2)+'"/>').join("");
  const presentation='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rId1"/></p:sldMasterIdLst><p:sldIdLst>'+ids+'</p:sldIdLst><p:sldSz cx="12192000" cy="6858000"/><p:notesSz cx="6858000" cy="9144000"/></p:presentation>';
  const relItems=slides.map((_,i)=>'<Relationship Id="rId'+(i+2)+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide'+(i+1)+'.xml"/>').join("");
  const presRels='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="slideMasters/slideMaster1.xml"/>'+relItems+'</Relationships>';
  const master='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldMaster xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr></p:spTree></p:cSld><p:clrMap accent1="accent1" accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5" accent6="accent6" bg1="lt1" bg2="lt2" folHlink="folHlink" hlink="hlink" tx1="dk1" tx2="dk2"/><p:sldLayoutIdLst><p:sldLayoutId id="1" r:id="rId1"/></p:sldLayoutIdLst></p:sldMaster>';
  const masterRels='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="../theme/theme1.xml"/></Relationships>';
  const layout='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldLayout xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" type="blank"><p:cSld name="Blank"><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr></p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sldLayout>';
  const layoutRels='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="../slideMasters/slideMaster1.xml"/></Relationships>';
  const theme='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="Controlled"><a:themeElements><a:clrScheme name="Controlled"><a:dk1><a:sysClr val="windowText" lastClr="000000"/></a:dk1><a:lt1><a:sysClr val="window" lastClr="FFFFFF"/></a:lt1><a:dk2><a:srgbClr val="1F1F1F"/></a:dk2><a:lt2><a:srgbClr val="F2F2F2"/></a:lt2><a:accent1><a:srgbClr val="4472C4"/></a:accent1><a:accent2><a:srgbClr val="ED7D31"/></a:accent2><a:accent3><a:srgbClr val="A5A5A5"/></a:accent3><a:accent4><a:srgbClr val="FFC000"/></a:accent4><a:accent5><a:srgbClr val="5B9BD5"/></a:accent5><a:accent6><a:srgbClr val="70AD47"/></a:accent6><a:hlink><a:srgbClr val="0563C1"/></a:hlink><a:folHlink><a:srgbClr val="954F72"/></a:folHlink></a:clrScheme><a:fontScheme name="Controlled"><a:majorFont><a:latin typeface="Arial"/><a:ea typeface="Microsoft YaHei"/><a:cs typeface="Arial"/></a:majorFont><a:minorFont><a:latin typeface="Arial"/><a:ea typeface="Microsoft YaHei"/><a:cs typeface="Arial"/></a:minorFont></a:fontScheme><a:fmtScheme name="Controlled"><a:fillStyleLst/><a:lnStyleLst/><a:effectStyleLst/><a:bgFillStyleLst/></a:fmtScheme></a:themeElements></a:theme>';
  return zip([{name:"[Content_Types].xml",data:e.encode(ct)},{name:"_rels/.rels",data:e.encode(rootRel)},{name:"ppt/presentation.xml",data:e.encode(presentation)},{name:"ppt/_rels/presentation.xml.rels",data:e.encode(presRels)},{name:"ppt/slideMasters/slideMaster1.xml",data:e.encode(master)},{name:"ppt/slideMasters/_rels/slideMaster1.xml.rels",data:e.encode(masterRels)},{name:"ppt/slideLayouts/slideLayout1.xml",data:e.encode(layout)},{name:"ppt/slideLayouts/_rels/slideLayout1.xml.rels",data:e.encode(layoutRels)},{name:"ppt/theme/theme1.xml",data:e.encode(theme)},...slideEntries,...slideRels])
}
export function pdf(title:string){
  const safe=title.normalize("NFKD").replace(/[^\x20-\x7e]/g," ").replace(/[()\\]/g,c=>"\\"+c).slice(0,120);
  const stream="BT /F1 14 Tf 72 760 Td (Automation Chief Engineer "+safe+") Tj 0 -24 Td /F1 10 Tf (R2-F10-GOLDEN-121 / R01 / controlled engineering baseline) Tj ET";
  const objects=["<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>","<< /Length "+stream.length+" >>\nstream\n"+stream+"\nendstream","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"];
  let body="%PDF-1.4\n%controlled\n";const offsets=[0];
  for(let i=0;i<objects.length;i++){offsets.push(e.encode(body).byteLength);body+=(i+1)+" 0 obj\n"+objects[i]+"\nendobj\n"}
  const xref=e.encode(body).byteLength;
  body+="xref\n0 "+(objects.length+1)+"\n0000000000 65535 f \n"+offsets.slice(1).map(v=>String(v).padStart(10,"0")+" 00000 n \n").join("");
  body+="trailer\n<< /Size "+(objects.length+1)+" /Root 1 0 R >>\nstartxref\n"+xref+"\n%%EOF\n";
  return e.encode(body)
}
export function openCsv(){const h=["Open Item ID","主题","当前状态","所需证据","关闭或启用条件","责任接口"],t=["DUT ICD/接口","产品语义","条件视觉","可选工位","安全","供应商","MES","POC","MSA/GR&R","FAT","SAT","客户验收","日历计划","ROI 输入"];return e.encode([h.join(","),...t.map((q,i)=>`OI-${String(i+1).padStart(3,"0")},${q},${i>=7&&i<=10?"PLANNED_NOT_EXECUTED":"待验证假设（需客户确认）"},受控证据,证据冻结并评审,Owner-${i+1}`)].join("\r\n"))}
export function readme(title:string,v:Envelope){return e.encode(`# ${title}｜交付说明\n\n- Delivery Contract: ${GOLDEN_PROFILE}\n- ZIP: 121 files / 119 payload files\n- 概念包络: ${v.widthMm} × ${v.depthMm} × ${v.heightMm} mm（${v.source}，ASM_NOT_VERIFIED）\n\n未执行的 POC、MSA/GR&R、FAT、SAT 不得写成 PASS；供应商、客户验收和现场条件缺少证据时进入开放项。整机概念 CAD 是受控工程概念，不冒充已制造设备。\n`)}
export function envelope(body:string):Envelope{const m=body.match(/(\d{3,4})\s*[x×*]\s*(\d{3,4})\s*[x×*]\s*(\d{3,4})\s*(?:mm|毫米)/i);if(m){const a=m.slice(1,4).map(Number);if(a.every(v=>v>=500&&v<=6000))return{widthMm:a[0],depthMm:a[1],heightMm:a[2],source:"STAGE-mechanical",assumed:true}}return{widthMm:1800,depthMm:1200,heightMm:1850,source:"RULE-CONCEPT-ENVELOPE-DEFAULT",assumed:true}}
export function svg(title:string,v:Envelope){return e.encode(`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="800"><rect width="100%" height="100%" fill="white"/><rect x="100" y="100" width="1000" height="600" fill="none" stroke="black" stroke-width="4"/><rect x="250" y="300" width="700" height="120" fill="none" stroke="black"/><text x="100" y="70" font-size="28">${x(title)} layout ${v.widthMm}x${v.depthMm} ASM_NOT_VERIFIED</text></svg>`)}
const ad=(b:Uint8Array)=>{let a=1,z=0;for(const v of b){a=(a+v)%65521;z=(z+a)%65521}return((z<<16)|a)>>>0};function zs(b:Uint8Array){const p:Uint8Array[]=[Uint8Array.from([0x78,1])];for(let o=0;o<b.length;o+=65535){const n=Math.min(65535,b.length-o),h=new Uint8Array(5),v=new DataView(h.buffer),last=o+n>=b.length;h[0]=last?1:0;v.setUint16(1,n,true);v.setUint16(3,(~n)&0xffff,true);p.push(h,b.slice(o,o+n))}const t=new Uint8Array(4);new DataView(t.buffer).setUint32(0,ad(b),false);p.push(t);const out=new Uint8Array(p.reduce((s,q)=>s+q.length,0));let k=0;for(const q of p){out.set(q,k);k+=q.length}return out}function ch(t:string,b:Uint8Array){const tb=e.encode(t),o=new Uint8Array(12+b.length),v=new DataView(o.buffer),c=new Uint8Array(4+b.length);v.setUint32(0,b.length,false);o.set(tb,4);o.set(b,8);c.set(tb);c.set(b,4);v.setUint32(8+b.length,crc(c),false);return o}
export function png(seed:number){const w=200,h=120,p=new Uint8Array(w*h*3);p.fill(248);for(let y=20;y<100;y++)for(let x0=20;x0<180;x0++){const edge=y===20||y===99||x0===20||x0===179||((x0+seed*7)%71===0&&y>35);if(edge){const i=(y*w+x0)*3;p[i]=30;p[i+1]=50+(seed*13)%120;p[i+2]=80+(seed*17)%120}}const raw=new Uint8Array(h*(1+w*3));let k=0;for(let y=0;y<h;y++){raw[k++]=0;raw.set(p.subarray(y*w*3,(y+1)*w*3),k);k+=w*3}const ih=new Uint8Array(13),iv=new DataView(ih.buffer);iv.setUint32(0,w,false);iv.setUint32(4,h,false);ih[8]=8;ih[9]=2;const q=[Uint8Array.from([137,80,78,71,13,10,26,10]),ch("IHDR",ih),ch("IDAT",zs(raw)),ch("IEND",new Uint8Array())],out=new Uint8Array(q.reduce((s,b)=>s+b.length,0));k=0;for(const b of q){out.set(b,k);k+=b.length}return out}
export function visuals():Entry[]{const a:Entry[]=[];for(let i=1;i<=90;i++)a.push({relativePath:`04_工程视觉/01_clean/VIS-CLEAN-${String(i).padStart(3,"0")}.png`,data:png(i),description:`Clean VIS ${i}`,ownerModule:"DigitalTwin",status:"ASM_NOT_VERIFIED",validationResult:"PNG_SIGNATURE_VALID"});for(let i=1;i<=4;i++)a.push({relativePath:`04_工程视觉/02_annotated/VIS-ANN-${String(i).padStart(3,"0")}.png`,data:png(100+i),description:`Annotated VIS ${i}`,ownerModule:"DigitalTwin",status:"ASM_NOT_VERIFIED",validationResult:"PNG_SIGNATURE_VALID"});for(let i=1;i<=2;i++)a.push({relativePath:`04_工程视觉/03_diagram/VIS-DIA-${String(i).padStart(3,"0")}.png`,data:png(200+i),description:`Diagram VIS ${i}`,ownerModule:"Documentation",status:"ENGINEERING_DIAGRAM",validationResult:"PNG_SIGNATURE_VALID"});return a}
export function views(prefix:"02_产品CAD与视图"|"03_整机概念CAD与视图",product=true):Entry[]{const n=product?["bottom","front","isometric","right","top"]:["cutaway","front","isometric","right","top"];return n.map((q,i)=>({relativePath:`${prefix}/${q}.png`,data:png(300+i+(product?0:10)),description:`${product?"Product":"Machine"} ${q} view`,ownerModule:product?"ProductCAD":"Mechanical",status:product?"CADCORE_DERIVED_VIEW":"ASM_NOT_VERIFIED",validationResult:"PNG_SIGNATURE_VALID"}))}
export function root(title:string){return`${title.normalize("NFKC").replace(/[\\/:*?"<>|]+/g,"-").replace(/\s+/g," ").trim().slice(0,60)||"非标自动化项目"}方案包`}
const ce=(v:string|number)=>/[",\r\n]/.test(String(v))?`"${String(v).replace(/"/g,'""')}"`:String(v);export function manifestCsv(r:Record<string,string|number>[]){const f=["File ID","File Name","Relative Path","Version","Description","Owner Module","Controlled Baseline Revision","Status","Validation Result","Size","SHA256","Customer"];return e.encode([f.join(","),...r.map(q=>f.map(k=>ce(q[k]??"")).join(","))].join("\r\n"))}export function manifestJson(r:Record<string,string|number>[]){return e.encode(JSON.stringify({profile:GOLDEN_PROFILE,schemaVersion:GOLDEN_SCHEMA,files:r},null,2))}
